#ifndef PLAYERINFOCONST_H
#define PLAYERINFOCONST_H

#define PLAYER_NAME "Lucy"
#define PLAYER_INITIAL_HEALTH 300.0f
#define PLAYER_INITIAL_DAMAGE 25.0f
#define PLAYER_INITIAL_WATER 100
#define PLAYER_INITIAL_HUNGER 100

#define DOG_INITIAL_NAME "Ajgi"
#define DOG_INITIAL_HEALTH 150.0f
#define DOG_INITIAL_DAMAGE 40.0f

#endif